FROM mcr.microsoft.com/devcontainers/typescript-node:0-20-bullseye

WORKDIR /app

# Define USERNAME environment variable
ENV USERNAME=node

# For saving bash history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R 1000:1000 /commandhistory \
    && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"
