version: '3'

services:
  app:
    user: '1000:1000'
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:delegated
      - bashhistory:/commandhistory:delegated
    ports:
      - '5173:5173'
    working_dir: /app
    environment:
      WATCHPACK_POLLING: 'true'
      NODE_ENV: 'development'
    command: ['sh', 'docker/app/startup.sh']
    # tty: true
    # stdin_open: true

volumes:
  node_modules:
  bashhistory:
